# Generated by Django 6.0.2 on 2026-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('Course_image', models.ImageField(upload_to='b_patient/static/media')),
            ],
        ),
    ]
