# Generated by Django 6.0.2 on 2026-02-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0003_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='course_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='course_image',
            field=models.ImageField(default=2, upload_to='b_practic/static/media'),
            preserve_default=False,
        ),
    ]
