# Generated by Django 6.0.2 on 2026-02-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0004_delete_courses_rename_first_name_user_course_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Courses',
        ),
    ]
