# Generated by Django 6.0.2 on 2026-02-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0005_rename_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
