# Generated by Django 6.0.2 on 2026-02-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0006_courses_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
