# Generated by Django 6.0.2 on 2026-02-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0007_alter_courses_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_video',
            field=models.FileField(default=2, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
