# Generated by Django 6.0.2 on 2026-02-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_practic', '0008_courses_course_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_video',
        ),
    ]
